#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored

def main():

    # ensure proper usage
    #if len(sys.argv) != 2:
    #    sys.exit("Usage: ./smile word")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    score=0

    # analyze word
    for i in sys.argv:
        med=analyzer.analyze(i)
        print(i)
        score=score+med
        print (med,score)
    if score > 0.0:
        print(colored(":)", "green"))
    elif score < 0.0:
        print(colored(":(", "red"))
    else:
        print(colored(":|", "yellow"))
    print(" Is the score ",score)

if __name__ == "__main__":
    main()
